# Generated by Django 4.2.6 on 2023-10-13 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.BigAutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
