# Generated by Django 4.2.6 on 2023-10-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_city_city_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_code',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_code',
            new_name='country',
        ),
    ]
