# Generated by Django 4.2.6 on 2023-10-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_rename_city_code_city_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.BigAutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
