# Generated by Django 4.2.6 on 2023-10-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_city_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
