# Generated by Django 4.2.6 on 2023-10-15 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_app', '0004_alter_productinformation_product_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinformation',
            name='product_verify',
            field=models.BooleanField(default=False),
        ),
    ]
